### PR TITLE
Support iPhone XS, iPhone XS Max and iPhone XR

### PR DESCRIPTION
**Pull request by EtienneLem**
Addresses #235

Basically always `toLowerCase` device names when comparing, because depending on where the device name comes from there are many different formatting, i.e.:
- iPhone Xs Max
- iPhone XS Max
- iPhone XS MAX

Also normalized the ʀ character (`R != ʀ`). Comparing is always false otherwise even when `toLowerCase()`.

### Note for Cordova users:
Until this is merged / released and Cordova updates its dependencies, you may want to add ios-sim to your `devDependencies` and replace in your workflow:

```sh
cordova run --target=DEVICE_TYPE_ID
```

by

```sh
ios-sim launch platforms/ios/build/emulator/YOUR_APP.app --devicetypeid=DEVICE_TYPE_ID
```

### CODE REVIEW

**Comment by shazron** [comment]
I just integrated #239 for ES6 support which is failing your changes. Rebase from master, thanks!

**Comment by shazron** [comment]
No need for rebase, I did it through Github. Now your PR is failing the eslint check, can you do:
```
npm install
npm run eslint -- --fix
```

**Comment by EtienneLem** [comment]
Done 🤘

**Comment by brodybits** [comment]
Thanks @EtienneLem for fixing this!

**Review by DIEGOHJ566 — COMMENTED** [review]
H

**Pull request merged**
