### PR TITLE
Simctl command now returning "isAvailble" instead of "availblity" with list command.

### PR DESCRIPTION
**Pull request by vibhor-ios**
Review : @shazron, @brodybits

### CODE REVIEW

**Comment by vibhor-ios** [comment]
@shazron, @brodybits can you please Review and merge this?

**Comment by erisu** [comment]
@vibhor-ios I noticed you are targeting the `8.x` branch. Can you please change the target branch to `master` so it can merged in?

**Comment by vibhor-ios** [comment]
@erisu We are currently using 8.x version. if we merge into master we have to change code our project. So can you please merge this into 8.x only?

**Comment by erisu** [comment]
I think it would be better if we merge this into master first so when `9.x` is released the changes are available and not lost.

For 8.x, it may be possible that we can cherry-pick the commit, but I will confirm with one other.

Even though it is possible to cherry-pick in the reverse order, our typical workflow is normally merging first into master and then cherry-picking them back into existing majors.

**Comment by vibhor-ios** [comment]
@erisu File structure of this repo is different in 8.x and master. File in which i made changes not exists on master branch, since we are using 8.0.1 version in our project this is working fine.

**Comment by erisu** [comment]
Thank you for clarifying about the project structure difference.

**Comment by erisu** [comment]
If you also have time to make the change and submit a PR for master, that would be awesome. This would help us make sure that when `9.x` is released, the fix is still available and that Xcode 11 will continue to work.

**Comment by vibhor-ios** [comment]
Hi @erisu can you please release "8.x" branch? So that i can use that release in our codebase.

**Comment by vibhor-ios** [comment]
@erisu Just reminder!!
can you please Release "8.x" branch?

**Comment by erisu** [comment]
@vibhor-ios `ios-sim@8.0.2` was already released a day ago. https://www.npmjs.com/package/ios-sim

**Pull request merged**
