### PR TITLE
Fix Cannot read property 'replace' of undefined

### PR DESCRIPTION
**Pull request by thomas-alrek**
Resolves issue #212

### CODE REVIEW

**Comment by Hirbod** [comment]
I can confirm: this fixed my problem! Thank you!

**Comment by shazron** [comment]
5.0.13 fixes this problem already I believe. 

I assume you encountered this in a Cordova project?
If so, can you do a `cd platforms/ios/cordova && npm install ios-sim@latest` from #212 to see if that fixes the problem

**Comment by Hirbod** [comment]
This does indeed fix this problem but I have to redo this every time I delete the platform

**Comment by shazron** [comment]
Yup I know, see #210 for an interim platform you can download until the new platform release comes out. I was wondering more whether this fix in this PR is for a similar, but different problem

**Comment by Hirbod** [comment]
Thanks mate!

**Comment by ThomasHambach** [comment]
Can confirm that this PR fixes the issue.

**Comment by lakinmohapatra** [comment]
When this will be merged with cordava ?

We should not face this issue again , research & add this patch .

**Comment by devansh1110** [comment]
This needs to be merged, please merge it. It passed all checks and for sure fixes the issue. 

Thanks

**Comment by shazron** [comment]
See https://github.com/phonegap/ios-sim/pull/213#issuecomment-308561256 
5.0.13 and cordova-ios@4.5.0 fixes this. Confirm this in your tests.

I'm not going to pull in a fix if its already fixed.

**Comment by eykjs** [comment]
Nice little fix! Updating the the ios-sim version didn't worked for me so I searched for another solution and yours worked 👍

**Comment by devansh1110** [comment]
@shazron I don't know but I used Terminal to download it, following the Getting Started Guide.
I'm new to GitHub, sorry

**Comment by brodybits** [comment]
I think the issue is already solved and we can close this one. If not then please explain asap.

**Pull request closed without merging**
